name: Run Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.actor == 'professoroakz' # Only runs if triggered by your username
    runs-on: reality-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run your script
        run: echo "Running script..."
